name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
   strategy:
   max-parallel: [4,8,12,16,20,24]
   matrix:
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: CI
        echo Add other actions to build,
        echo test, and deploy your project.
